services:
  # PostgreSQL Database
  database:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=nest_office
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Backend NestJS API
  backend:
    build:
      context: ./back
      target: development
    command: ["pnpm", "start:dev"]
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_HOST=database
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=nest_office
    ports:
      - "3000:3000"
    volumes:
      - ./back/src:/app/src
      - /app/node_modules
    networks:
      - app-network
    depends_on:
      - database

  # Frontend Next.js Application
  frontend:
    build:
      context: ./front
      target: development
    command: ["pnpm", "dev"]
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    ports:
      - "3001:3000"
    volumes:
      - ./front/app:/app/app
      - ./front/components:/app/components
      - ./front/lib:/app/lib
      - ./front/hooks:/app/hooks
      - ./front/public:/app/public
      - /app/node_modules
      - /app/.next
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
