import { Permission } from '../enums/permissions.enum';
import { UserRole } from '../../users/entities/user.entity';

// Use UserRole enum which matches what's stored in the database
export const RolePermissions: Record<string, Permission[]> = {
  [UserRole.ADMIN]: [
    Permission.CREATE_OFFICE,
    Permission.UPDATE_OFFICE,
    Permission.DELETE_OFFICE,
    Permission.VIEW_OFFICE,
    Permission.ASSIGN_MANAGER,
    Permission.REMOVE_MANAGER,
    Permission.VIEW_REPORTS,
    Permission.EXPORT_REPORTS,
    Permission.CREATE_USER,
    Permission.UPDATE_USER,
    Permission.DELETE_USER,
    Permission.VIEW_USER,
    Permission.MANAGE_OFFICE_TYPES,
    Permission.MANAGE_LOCATIONS,
    Permission.ASSIGN_CITY_ADMIN,
    Permission.ASSIGN_STATE_ADMIN,
    Permission.ASSIGN_COUNTRY_ADMIN,
    Permission.MANAGE_HIERARCHICAL_ADMINS,
  ],
  [UserRole.COUNTRY_ADMIN]: [
    Permission.VIEW_SCOPE_OFFICES,
    Permission.MANAGE_SCOPE_OFFICES,
    Permission.VIEW_SCOPE_USERS,
    Permission.MANAGE_SCOPE_USERS,
    Permission.ASSIGN_CITY_ADMIN,
    Permission.ASSIGN_STATE_ADMIN,
    Permission.VIEW_REPORTS,
    Permission.EXPORT_REPORTS,
    Permission.ASSIGN_MANAGER,
    Permission.REMOVE_MANAGER,
  ],
  [UserRole.STATE_ADMIN]: [
    Permission.VIEW_SCOPE_OFFICES,
    Permission.MANAGE_SCOPE_OFFICES,
    Permission.VIEW_SCOPE_USERS,
    Permission.MANAGE_SCOPE_USERS,
    Permission.ASSIGN_CITY_ADMIN,
    Permission.VIEW_REPORTS,
    Permission.EXPORT_REPORTS,
    Permission.ASSIGN_MANAGER,
    Permission.REMOVE_MANAGER,
  ],
  [UserRole.CITY_ADMIN]: [
    Permission.VIEW_SCOPE_OFFICES,
    Permission.MANAGE_SCOPE_OFFICES,
    Permission.VIEW_SCOPE_USERS,
    Permission.MANAGE_SCOPE_USERS,
    Permission.VIEW_REPORTS,
    Permission.EXPORT_REPORTS,
    Permission.ASSIGN_MANAGER,
    Permission.REMOVE_MANAGER,
  ],
  [UserRole.USER]: [Permission.VIEW_OFFICE, Permission.VIEW_USER],
  [UserRole.MANAGER]: [
    Permission.VIEW_OFFICE,
    Permission.UPDATE_OFFICE,
    Permission.VIEW_USER,
    Permission.VIEW_REPORTS,
  ],
};
