version: "3.9"

services:
  app:
    build:
      context: .
      target: production
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3000
