version: "3.9"

services:
  app:
    build:
      context: .
      target: development
    command: ["pnpm", "start:dev"]
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - PORT=3000
